import { Rubik } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material";
import theme from "@/theme";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  display: "swap", // Add this
  preload: true, // Add this
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased`}
        suppressHydrationWarning
      >
        <AppRouterCacheProvider>
          <ThemeProvider {...{ theme }}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
