import { Rubik } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material";
import theme from "@/theme";
import ReduxProvider from "@/providers/redux-provider";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  display: "swap", // Add this
  preload: true, // Add this
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang={'en'}>
      <body
        className={`${rubik.variable} antialiased`}
        suppressHydrationWarning
      >
        <AppRouterCacheProvider>
          <ThemeProvider {...{ theme }}>
              <ReduxProvider>{children}</ReduxProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
